SELECT * FROM CUSTOMERS;

SET SERVEROUTPUT ON;
CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE ON CUSTOMERS
FOR EACH ROW
BEGIN
    :NEW.LASTMODIFIED := SYSDATE;
    
    DBMS_OUTPUT.PUT_LINE('Updated CUSTOMERID = ' || :NEW.CUSTOMERID || ' with current LASTMODIFIED timestamp.');
    
END UPDATECUSTOMERLASTMODIFIED;
/

